stages:
  # - build
  # - test
  - deploy

# build:
#   stage: build
#   script:
#     - sudo apt-get install npm=8.19.2
#     - npm run build
#   tags:
#     - deploy main

# test:
#   stage: test
#   script:
#     - npm test

deploy:
  stage: deploy
  script:
    - touch key.pem
    - ls -la key.pem
    - echo "$EC2_KEY"
    - echo "$EC2_KEY" > key.pem
    - echo "key written"
    - cat key.pem | echo
    - chmod 400 key.pem
    - ssh -i key.pem ubuntu@ec2-54-173-216-235.compute-1.amazonaws.com "cd /huddleup/webapp && git checkout main && git pull && npm install && npm run build && pm2 start npm --name "webapp" -- start"
  tags:
    - deploy main
# deploy:
#   stage: deploy
#   script:
#     - git checkout main
#     - git pull
#     - npm install
#     - npm run build
#     - pm2 start npm --name "webapp" -- start'
#   only:
#     - main
#   tags:
#     - deploy main
