stages:
  - build

build:
  stage: build
  image: npm:8.19.2
  script:
    - echo "$EC2_KEY" > key.pem
    - chmod 400 key.pem
    - ssh -o "StrictHostKeyChecking no" -i "key.pem" ls && cd huddleup && ls && cd webapp && ls && npm install && npm run build && pm2 start npm --name "webapp" -- start'
  tags:
    - deploy main
