stages:
  - build

build:
  stage: build
  image: ubuntu:20.04
  script:
    - echo "$EC2_KEY" > key.pem
    - chmod 400 key.pem
    - ssh -o "StrictHostKeyChecking no" -i "key.pem" ubuntu@ec2-54-173-216-235.compute-1.amazonaws.com 'ls && cd huddleup && ls && cd webapp && ls && sudo npm install && sudo npm run build && sudo pm2 start npm --name "webapp" -- start'
  tags:
    - deploy main
