stages:
  - generateKey
  - build

generateKey
  stage: generateKey
  image: ubuntu:latest
  script:
    - echo "$EC2_KEY"
    - echo "$EC2_KEY" > key.pem
    - chmod 400 key.pem
  tags:
    - deploy main

build:
  stage: build
  image: node:19.0.0  
  script:
    - ssh -o "StrictHostKeyChecking no" -i "key.pem" ubuntu@ec2-54-173-216-235.compute-1.amazonaws.com 'ls && cd huddleup && ls && cd webapp && ls && npm --version && npm install && npm run build && pm2 start npm --name "webapp" -- start'
  tags:
    - deploy main
