stages:
  - build
  # - test
  - deploy

build:
  stage: build
  script:
    - cd ..
    - ls
  tags:
    - deploy main

# test:
#   stage: test
#   script:
#     - npm test

deploy:
  stage: deploy
  script:
    - git checkout main
    - git pull
    - npm install
    - npm run build
    - pm2 start npm --name "webapp" -- start'
  only:
    - main
  tags:
    - deploy main
