stages:
  - build

build:
  stage: build
  image: ubuntu:latest # Use Node.js version 14
  script:
    - echo "$EC2_KEY"
    - echo "$EC2_KEY" > key.pem
    - chmod 400 key.pem
    - ssh -o "StrictHostKeyChecking no" -i "key.pem" ubuntu@ec2-54-173-216-235.compute-1.amazonaws.com 'ls && cd huddleup && ls && cd webapp && ls && export PATH="$PATH:/home/ubuntu/.nvm/versions/node/v19.0.0/bin/npm/bin" && npm install && npm run build && pm2 start npm --name "webapp" -- start'
  tags:
    - deploy main
