stages:
  - build

build:
  stage: build
  image: ubuntu:latest # Use Node.js version 14
  script:
    - echo "$EC2_KEY"
    - echo "$EC2_KEY" > key.pem
    - ssh -o "StrictHostKeyChecking no" -i "key.pem" ubuntu@ec2-54-173-216-235.compute-1.amazonaws.com
  tags:
    - deploy main
